name: Synchronizacja Discord
on:
  schedule:
    - cron: '*/5 * * * *' # Sprawdza co 5 minut
  workflow_dispatch: # Pozwala odpalić ręcznie guzikiem w zakładce Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pobierz wiadomości
        env:
          BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: '1503491827884625990'
        run: |
          curl -H "Authorization: Bot $BOT_TOKEN" \
               "https://discord.com/api/v10/channels/$CHANNEL_ID/messages?limit=5" > ogloszenia.json
      - name: Zapisz do repozytorium
        run: |
          git config --global user.name 'YangWu-Bot'
          git config --global user.email 'bot@yangwu.pl'
          git add ogloszenia.json
          git commit -m "Aktualizacja ogłoszeń z Discorda" || exit 0
          git push
