name: Aktualizuj Ogłoszenia

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod repozytorium
        uses: actions/checkout@v4

      - name: Ustaw najnowszą wersję Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Ta linijka naprawi błąd "fetch is not defined"!

      - name: Uruchom skrypt bota
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: node fetch_discord.js

      - name: Automatyczny commit i push zmian
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatyczna aktualizacja ogłoszeń z Discorda"
